install:
		install -d -g bin -o root -m 0775 $(DATADIR)
		install -d -g bin -o root -m 0775 $(DESKTOPDIR)
		install -d -g bin -o root -m 0775 $(PNGDIR)

		install -g bin -o root -m 0664 GUISetup.desktop $(DESKTOPDIR)
		install -g bin -o root -m 0664 SDRHelp.desktop  $(DESKTOPDIR)
		install -g bin -o root -m 0664 UWSDR.desktop    $(DESKTOPDIR)
		install -g bin -o root -m 0664 Skeleton.desktop $(DATADIR)

		install -g bin -o root -m 0664 GUISetup.png $(PNGDIR)
		install -g bin -o root -m 0664 SDRHelp.png  $(PNGDIR)
		install -g bin -o root -m 0664 UWSDR.png    $(PNGDIR)
